### PR TITLE
CMake tweaks for MacOSX

### PR DESCRIPTION
**Pull request by samusangio**
Tweaked CMake to work under MacOSX w/ clang

@vbelov42

### CODE REVIEW

**Comment by vbelov42** [comment]
Hi, @samusangio 
Couple of questions:
1. I also saw that `find_package(PythonLibs)` is likely to happen _after_, `find_package(PythonInterp)` (lines 54-56). But deep inside, library is required for interpreter, and not vice-versa. So There could be a library installed without interpreter. Your code will miss that completely.
2. Finding Boos, are lines 95-99 written for MacOS and not Windows? Why lines 96 and 98 are the same?
3. We require only one component now, but this may change in future. Shouldn't line 102 be more specific and for APPLE only?

**Comment by vbelov42** [comment]
Regarding (1), may I suggest, that we search for `find_package(PythonLibs ${PYTHONLIBS_VERSION_STRING})`, if there is PYTHONINTERP_FOUND, but do wild `find_package(PythonLibs)` if it wasn't. And only if everything failed, then we call for CMT.

**Comment by samusangio** [comment]
Hi @vbelov42 

1. on second thought, I agree with finding PYTHONLIBS first and only PYTHONINTERP afterward. This makes it easier to change PYTHON install from the CMAKE command line. I do want to force matching of both libs and executable though to avoid linking issues.  In the last commit I also removed the search for python3 ahead of python2 since we are not ready to switch to python3 yet
2. The boost finding logic should work on all systems but I haven't checked
3. The line `set(Boost_PYTHON_LIBRARY ${Boost_LIBRARIES})` seemed necessary but I'm not quite sure why and whether it is only needed for APPLE.

**Comment by vbelov42** [comment]
@samusangio 
1. Ok, this seems good. Also sniper is not only for us, and system python is still 2.7.
2. The question is 'you wrote it for APPLE and you tested it for APLLE', right?
3. Of course setting of `Boost_PYTHON_LIBRARY` is necessary, but the thing is, that `${Boost_LIBRARIES}` can contain more. Actually all requested libraries are collected there. That's why we can't simply dump everything to `Boost_PYTHON_LIBRARY`. Do you know why it isn't set in FindBoost.cmake naturally?  What version of cmake do you use?

**Comment by vbelov42** [comment]
2. There is no full clearance, but it seems, that on Windows boost_python uses 2-digit suffix. So this can remain as it is.

**Comment by zoujh** [comment]
Hi @samusangio and @vbelov42 

Thank you for the efforts. It is great that we have more contributors and discussions. I believe it is helpful to make SNiPER better.
As @vbelov42 mentioned, generally ${Boost_LIBRARIES} contains more than Boost_PYTHON_LIBRARY. We should set Boost_PYTHON_LIBRARY precisely rather than a superset. I am not very familiar with cmake. Is there any suggestions from @vbelov42 ?
For the testing on MacOS, I will find some volunteers (who have APPLE) for verification.

Best regards,

**Comment by vbelov42** [comment]
Idea is to find target libraries from the list and set appropriate variables. The same task is done several lines below for boost found by CMT. I assume we can copy.

**Comment by zoujh** [comment]
Hi @samusangio Would you please revise the setting of `Boost_PYTHON_LIBRARY`? It's better for us to set it precisely other than `Boost_LIBRARIES`. Thank you!

**Comment by samusangio** [comment]
Hi @zoujh @vbelov42 `Boost_PYTHON_LIBRARY` should be fixed now.

**Pull request merged**
