### PR TITLE
CMake tweaks

### PR DESCRIPTION
**Pull request by samusangio**
A few tweaks to cmake. 

I'm now requiring boost version >= 1.67 to increase portability across different systems and simply cmake handling of boost python

Also including a mac-specific change to force creation of .so library (instead of .dylib which do not always import natively in python)

Finally added update to PATH env variable in setup.sh created by cmake

cc: @mirguest @vbelov42

### CODE REVIEW

**Comment by vbelov42** [comment]
Hi @samusangio. If simplification of CMake code is the only reason for bumping Boost version, I'd say it's an overkill. First, we'll loose compatibility with default RHEL7, this may be important for other people. Second, the same can be done by creating a flexible list of modules to search for in find_package(), which we will, probably, end up with anyway, as use of Boost will grow. Third, we need to workaround different Boost_PYTHON*_LIBRARY anyway, so you can't remove it this simple.

**Comment by samusangio** [comment]
Hi @vbelov42 I did not realize that RHEL7 was still using Boost 1.53 (and yes, I was also being a little lazy).  I've gone back to require only Boost >= 1.53 but also handle the Boost_python suffix change with Boost >= 1.67.    Please test.   Let me also know if there is a more elegant way to handle this

**Comment by heather999** [comment]
If we are going to push for dropping CMT, we may want to get this PR merged or closed if it is not going to be pulled into master here.  Are there any other updates used locally at LLNL?  While RH7 may use Boost 1.53 by default, users of sniper may very likely use Boost >= 1.67, so we need to support both.

**Comment by zoujh** [comment]
I suppose it is time to drop CMT and move to CMake completely. See the latest updates #18 . Please comment on it if there is any problems.

**Comment by zoujh** [comment]
I will leave #13 be open for further discussion, and close this one.

**Pull request closed without merging**
